# Generated by Django 3.2.6 on 2021-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.URLField(blank=True, null=True)),
                ('short', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
