# Generated by Django 3.2.6 on 2021-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
