# Generated by Django 3.2.6 on 2021-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_alter_url_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visit_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
