# Generated by Django 3.2.6 on 2021-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0003_url_visit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='visit_number',
            field=models.BigIntegerField(default=1),
        ),
    ]
